### ISSUE TITLE
Quantitative Example in Empirical Contributions

### ISSUE THREAD

**Issue by jayfo** [uwcse510/web-cse510-22wi#12]
The "Empirical" papers are all qualitative.

Can we keep one of those, but replace 2 with quantitative:
- something small-scale (e.g., a human performance lab study)
- something large-scale (e.g., large dataset analysis)

"Empirical" is a huge bucket, want some variety of method in that.

**Comment by anantmittal** [comment]
Sure thing.

**Comment by jayfo** [comment]
One possibility would be to move this from Dataset to Empirical, if you find another Dataset contribution:

https://doi.org/10.1145/3411764.3445367

That paper has a dataset, but it's not shared. So that can be an interesting observation there, or it could be moved to Empirical since it's mostly just reporting that very thorough empirical examination.

**Comment by anantmittal** [comment]
@jayfo How about one of these for `something small-scale`? 
https://dl.acm.org/doi/10.1145/3411764.3445322
https://dl.acm.org/doi/10.1145/3411764.3445578

If you approve I can move https://doi.org/10.1145/3411764.3445367 to Empirical and look for more dataset papers for the `Dataset` section.

**Comment by jayfo** [comment]
Sure, let's use Tactile Fixations.  It has less of an artifact confound in there.

**Comment by jayfo** [comment]
Fixed in #24
